---
title: "Visualizing Preferences"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(janitor)
library(readxl)
library(fmsb)
library(tidyverse)
```

```{r read in data, include = FALSE}

data1 <- read_excel("preferences.xlsx") 

# read in data 

```

```{r modify data, include = FALSE}

data2 <- data1 %>% 
  mutate("Country" = ...1) %>% 
  select(!...1) %>% clean_names() %>% 
  pivot_longer(ceasefire:local_elections, names_to = "Issue", values_to = "Priority") %>% 
  pivot_wider(id_cols = Issue, names_from = country, values_from = Priority) 

#clean up tibble--rename columns to names that are easy to work with and flip tibble 

```


```{r}
datad1 <- data2 %>% 
  filter(Issue %in% c("ceasefire", "smm", "un_pk_force"))

# select just the issues that were discussed on day one of the simulation 

datad1 <- as.data.frame(datad1) %>% select(OSCE:LPR)

# save it as a dataframe 

rownames(datad1) <- c("Ceasefire", "OSCE SMM", "UN Peacekeepers")

# rename the rows 

datad1 <- rbind(rep(5,5) , rep(2,5) , datad1)

# add rows that will specify the limits of the radarchart

colors_border=c("mediumorchid1", "dodgerblue", "blue")

# create a vector of colors to input into radarchart 

png(filename = "day1.png", res = 70, height = 410, width = 676)

radarchart(datad1, pcol = colors_border, pty = 32, plty =1, plwd=3, cglcol = "black", title = "Day 1", seg = 3)
legend(x= 1.5, y= 1.2, legend = rownames(datad1[-c(1,2),]), bty = "n", pch=20 , col=colors_border , text.col = "black", cex=1, pt.cex=2)

dev.off()
```

```{r}

datad2 <- data2 %>% 
  filter(Issue %in% c("constitution", "status_dpr_lpr", "local_elections"))

# select just the issues that were discussed on day two of the simulation 

datad2 <- as.data.frame(datad2) %>% select(OSCE:LPR)

# save it as a dataframe 

rownames(datad2) <- c("Constition", "Status DPR/LPR", "Local Elections")

# rename the rows

datad2 <- rbind(rep(5,5) , rep(2,5) , datad2)

# add rows that will specify the limits of the radarchart

colors_border2=c("red4", "red", "darkorange")

# create a vector of colors to input into radarchart 

png(filename = "day2.png", res = 70, height = 410, width = 676)

radarchart(datad2, pcol = colors_border2, pty = 32, plty =1, plwd=3, cglcol = "black", title = "Day 2", seg = 3)

# create the radarchart, specifying the types of line and points, adding a title 

legend(x= 1.5, y= 1.2, legend = rownames(datad2[-c(1,2),]), bty = "n", pch=20 , col=colors_border2 , text.col = "black", cex=1, pt.cex=2)

# add a legend 

dev.off()

# save it as a png file 

```

```{r}

data3 <- as.data.frame(data2)

data4 <- data3 %>% select(OSCE:LPR) 

rownames(data4) <- c("Ceasefire","OSCE SMM","UN Peacekeepers","Constitution","Status LPR/DPR","Local Elections")

data4 <- rbind(rep(5,5) , rep(2,5) , data4)

colors_border=c("cadetblue", "dodgerblue", "blue", "navy", "mediumvioletred", "mediumorchid1")
labels = c("Ceasefire", "OSCE SMM", "UN Peacekeeping Force", "Constitution", "Status LPR/DPR", "Local Elections")

png(filename = "preferences.png", res = 70, height = 410, width = 676)

radarchart(data4, pcol = colors_border, pty = 1, plty =1, plwd=2, cglcol = "black", title = "Intensity of Actor Preferences", seg = 3)

# create radar chart, specifying the types of line and points, adding a title  

legend(x= 1.5, y= 1.2, legend = rownames(data4[-c(1,2),]), bty = "n", pch=20 , col=colors_border , text.col = "black", cex=1, pt.cex=2)

# add a legend

dev.off()

# save it as a png file 

```

